apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: mycluster
  region: ap-south-1


nodeGroups:
   - name: nodegrp1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: myekskey
   
   - name: nodegrp2
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: myekskey
