apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namesp1
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat 

resources:
  - efs-provisioner.yaml
  - rbac.yaml
  - create-sc.yaml
  - mysql-deploy.yaml
  - wordpress-deploy.yaml